server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/crypto_project

  sql:
    init:
      mode: always
      platform: postgres

  flyway:
    enabled: false
    schemas: crypto_fetcher_flyway_schema
    default-schema: crypto_fetcher_flyway_schema
    table: crypto_fetche_flyway_history
    locations: classpath:db/postgresql
    baseline-on-migrate: true

  jpa:
    properties:
      hibernate:
        default_schema: crypto_fetcher_flyway_schema
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect



